[metadata]
creation_date = "2025/06/16"

[rule]
author = ["JP"]
description = "This alert detect vulnerability test executed by tools[Nikto, Nmap, Nessus]"
from = "now-9m" 
index = ["logs-endpoint.events.process-*"]
name = "Web Scanner Activity - Nmap, Nessus and nikto"
risk_score = 25
severity = "high"
risk_score = 25
severity = "high"
rule_id = "123adads-daf5-4e1a-9049-ff79b5254704"
tags = ["example"]
type = "query"

query = '''
event.dataset: zeek and user_agent.original:*Nmap* or user_agent.original:*Nikto* or user_agent.original:*Nessus*
'''

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"

[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"
